title: Security Program Scorecards
tagline: Assess your security program health with interactive metrics

hero:
  title: "Build better security programs,<br>one metric at a time"
  subtitle: "Quickly assess your security organization's health and benchmarks"

footer:
  text: "Built for security leaders"
  year: 2024 