title: Security Program Scorecards
tagline: Assess your security program health with interactive metrics

hero:
  title: "Build better security programs,<br>one metric at a time"
  subtitle: "Benchmark your security organization health against industry standards"

footer:
  text: "Built by and for Security Leaders"
  year: 2025